site_name: sait-data-475
nav:
  - Home: index.md
  - FAQ: faq.md
theme:
  name: material
  favicon: https://raw.githubusercontent.com/sait-data-475/logo/main/logo.png
  logo: https://raw.githubusercontent.com/sait-data-475/logo/main/logo.png
  font:
    text: Roboto
  palette:
    - scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
    - content.code.copy
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: True
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
