site_name: sait-data-475
nav:
  - Home: index.md
  - Install: install.md
  - FAQ: faq.md
  - Extra: extra.md
theme:
  name: material
  favicon: https://raw.githubusercontent.com/sait-data-475/logo/main/logo.png
  logo: https://raw.githubusercontent.com/sait-data-475/logo/main/logo.png
  font:
    text: Roboto
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
  features:
    - header.autohide
    - navigation.top
    - navigation.footer
    - content.code.copy
plugins:
  - search
  - tags
  - glightbox:
      auto_caption: true
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: timeago
      enable_creation_date: true
markdown_extensions:
  - def_list
  - attr_list
  - md_in_html
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
repo_name: sait-data-475.github.io
repo_url: https://github.com/sait-data-475/sait-data-475.github.io
extra:
  social:
    - icon: fontawesome/solid/house
      link: https://sait-data-475.github.io/
    - icon: fontawesome/brands/github
      link: https://github.com/sait-data-475
